services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: restaurant-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped