# Gemini AI 专用配置
spring:
  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com
      api-key: ${GEMINI_API_KEY}
      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash