# Groq AI 专用配置
spring:
  ai:
    openai:
      base-url: https://api.groq.com
      api-key: ${GROQ_API_KEY}
      chat:
        completions-path: /openai/v1/chat/completions
        options:
          model: llama-3.1-70b-versatile